# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f36ffff3ed4c067c2bb9f9f935df3c515f2ce0d8b03a36bb659325a0250a08a4d7f7840ca4dd63b85263209907e6fff446e64d7dfe3abc6454cb8343479ba0d

test:
  secret_key_base: 1cd56f4e3ea9417492f61ad8adc3e55bbf2c5884f2cfc7fc85902d392b345b9455316ed5cf66ddee6e796d022a33298108e61d98e302e834021186ba7ca2b85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
